// Narration for tooltip beats: plays the pre-generated edge-tts clip
// (public/tts/<lang>/<key>.mp3, generated by `npm run tts`) in lockstep with
// the caption — the caption window equals the clip duration, and the clip's
// playbackRate mirrors the demo speed multiplier (wait() slices scale the
// same way, so caption, voice and script stay in sync at 1×/2×/4×).
// Pause / resume / stop of the demo are mirrored onto the audio element via
// the demo store subscription.
import i18n from "@/i18n";
import { useDemoStore } from "./demoStore.ts";

/** Local file: metadata resolves fast; past this the clip is abandoned. */
const METADATA_TIMEOUT_MS = 1200;
/** The manifest must not hold a beat hostage either. */
const MANIFEST_TIMEOUT_MS = 1500;

/** 32-bit FNV-1a over UTF-16-LE bytes (same function as tts/generate.py). */
function fnv1a(text: string): string {
  const buffer = new ArrayBuffer(text.length * 2);
  const view = new Uint16Array(buffer);
  for (let i = 0; i < text.length; i++) {
    view[i] = text.charCodeAt(i);
  }
  const bytes = new Uint8Array(buffer);
  let h = 0x811c9dc5;
  for (const byte of bytes) {
    h ^= byte;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16);
}

/**
 * public/tts/manifest.json records the caption each clip was generated from.
 * Captions are edited far more often than audio is regenerated, so before
 * playing a clip we check the caption still hashes to the recorded value; a
 * mismatch falls back to caption-only instead of voicing yesterday's words.
 * A missing manifest (or a key it does not know) means "no check".
 */
let manifest: Promise<Record<string, Record<string, string>> | null> | null = null;

function loadManifest(): Promise<Record<string, Record<string, string>> | null> {
  if (!manifest) {
    manifest = new Promise((resolve) => {
      const timer = window.setTimeout(() => resolve(null), MANIFEST_TIMEOUT_MS);
      void fetch(`${import.meta.env.BASE_URL}tts/manifest.json`)
        .then((r) => (r.ok ? r.json() : null))
        .then((j) => resolve(j as Record<string, Record<string, string>> | null))
        .catch(() => resolve(null))
        .finally(() => window.clearTimeout(timer));
    });
  }
  return manifest;
}

class Narration {
  private audio: HTMLAudioElement | null = null;
  /** In-flight start() resolver — settled by stop() so Esc never hangs a beat. */
  private pending: ((ms: number | null) => void) | null = null;
  /** One console warning per stale clip, not one per beat. */
  private warnedStale = new Set<string>();

  constructor() {
    if (typeof window === "undefined") return;
    useDemoStore.subscribe((s, prev) => {
      const a = this.audio;
      if (s.speed !== prev.speed && a) this.applyRate(a, s.speed);
      if (s.status === prev.status || !a) return;
      if (s.status === "playing") {
        if (a.paused && !a.ended) void a.play().catch(() => {});
      } else if (s.status === "paused") {
        if (!a.paused) a.pause();
      } else {
        this.stop(); // idle | done
      }
    });
  }

  private applyRate(a: HTMLAudioElement, speed: number): void {
    try {
      a.playbackRate = Math.min(Math.max(speed, 0.25), 16);
    } catch {
      /* not loaded yet — start() re-applies right after setting src */
    }
  }

  /** No clip is current, or the current clip has spoken its last frame. */
  finished(): boolean {
    const a = this.audio;
    return !a || a.ended;
  }

  /** Voice time left in the current clip (0 when ended), null when no clip. */
  remainingMs(): number | null {
    const a = this.audio;
    if (!a) return null;
    if (!Number.isFinite(a.duration)) return null;
    return Math.max(0, a.duration * 1000 - a.currentTime * 1000);
  }

  /**
   * Start the clip for `key` in the current UI language. Resolves with the
   * clip duration in ms only once playback is verifiably under way (metadata
   * known AND play() fulfilled), or null when the clip is missing / metadata
   * stalls / playback is blocked — the caller then falls back to the scripted
   * caption window.
   */
  start(key: string): Promise<number | null> {
    this.stop();
    const lang = (i18n.language ?? "zh").toLowerCase().startsWith("en") ? "en" : "zh";
    const caption = i18n.t(key, { ns: "demo", defaultValue: key }) as string;
    // Stale-clip guard: play only if the clip was generated from THIS caption.
    return loadManifest()
      .then((m) => {
        const recorded = m?.[lang]?.[key];
        if (recorded && recorded !== fnv1a(caption)) {
          if (!this.warnedStale.has(key)) {
            this.warnedStale.add(key);
            console.warn(
              `[demo] tts/${lang}/${key}.mp3 does not match the current caption — ` +
                "playing caption only; run: npm run tts -- --force",
            );
          }
          return null;
        }
        return this.playClip(key, lang);
      })
      .catch(() => null);
  }

  private playClip(key: string, lang: string): Promise<number | null> {
    const a = new Audio();
    a.preload = "auto";
    this.audio = a;
    return new Promise<number | null>((resolve) => {
      let settled = false;
      let durationMs: number | null = null;
      let playing = false;
      const settle = (ms: number | null): void => {
        if (settled) return;
        settled = true;
        if (this.pending === settle) this.pending = null;
        window.clearTimeout(timer);
        resolve(ms);
      };
      // Both halves must land: duration known, and playback actually started
      // (a blocked play() must not hand the runner a phantom duration).
      const maybeSettle = (): void => {
        if (durationMs !== null && playing) settle(durationMs);
      };
      this.pending = settle;
      // Metadata never arrives → drop the clip; caller uses scripted ms.
      const timer = window.setTimeout(() => this.stop(), METADATA_TIMEOUT_MS);

      a.addEventListener(
        "loadedmetadata",
        () => {
          if (Number.isFinite(a.duration) && a.duration > 0) {
            durationMs = a.duration * 1000;
            maybeSettle();
          } else {
            this.stop();
          }
        },
        { once: true },
      );
      a.addEventListener("error", () => {
        if (this.audio === a) this.audio = null;
        settle(null);
      });
      a.addEventListener("ended", () => {
        if (this.audio === a) this.audio = null;
      });
      a.src = `${import.meta.env.BASE_URL}tts/${lang}/${key}.mp3`;
      this.applyRate(a, useDemoStore.getState().speed);
      // Autoplay blocked / decode failure → caption-only fallback.
      void a
        .play()
        .then(() => {
          playing = true;
          maybeSettle();
        })
        .catch(() => {
          if (this.audio === a) this.audio = null;
          settle(null);
        });
    });
  }

  stop(): void {
    const p = this.pending;
    this.pending = null;
    p?.(null);
    const a = this.audio;
    this.audio = null;
    if (!a) return;
    a.pause();
    a.removeAttribute("src"); // abort buffer fetch
    void a.load();
  }
}

export const narration = new Narration();
