#!/usr/bin/env python3
"""Generate demo narration: transcripts + edge-tts audio (zh/en, female voices).

Reads the five one-click demo scripts (src/demo/scripts.ts) and the zh/en demo
locale files, then for every tooltip beat writes:

  tts/transcript.<lang>.md       ordered captions per script (zh + en)
  public/tts/<lang>/<key>.mp3    narration audio, served by the app at
                                 /tts/<lang>/<key>.mp3

Usage:
  bash tts/generate.sh [--force] [--transcript-only]
  tts/.venv/bin/python tts/generate.py
"""
from __future__ import annotations

import argparse
import asyncio
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import edge_tts
except ImportError:  # pragma: no cover
    sys.exit("edge-tts is not installed — run: bash tts/generate.sh")

ROOT = Path(__file__).resolve().parent.parent
HERE = Path(__file__).resolve().parent
SCRIPTS_TS = ROOT / "src" / "demo" / "scripts.ts"
AUDIO_DIR = ROOT / "public" / "tts"
LANGS = ("zh", "en")
# Both female neural voices.
VOICES = {"zh": "zh-CN-XiaoxiaoNeural", "en": "en-US-AriaNeural"}
CONCURRENCY = 4
RETRIES = 3

SCRIPT_RE = re.compile(r"const\s+\w+\s*:\s*DemoScript\s*=\s*\{(.*?)\n\};", re.S)
HEAD_RE = re.compile(r'id:\s*"(?P<id>[^"]+)",\s*nameKey:\s*"(?P<nameKey>[^"]+)"')
BEAT_RE = re.compile(
    r'\{ id: "(?P<id>[^"]+)", chapter: "(?P<chapter>[^"]+)", '
    r'action: \{ t: "tooltip", key: "(?P<key>[^"]+)", ms: (?P<ms>\d+)(?P<rest>[^}]*)\} \}'
)
# Everything after `ms` is routing for the demo director (`focus`, `zoom`), so
# the tail is captured loosely: a stricter pattern once dropped every zoom beat
# out of the transcript without a word.
FOCUS_RE = re.compile(r'focus:\s*"(?P<focus>[^"]+)"')
ZOOM_RE = re.compile(r"zoom:\s*(?P<zoom>[\d.]+)")
TOOLTIP_COUNT_RE = re.compile(r't:\s*"tooltip"')

TITLES = {
    "zh": "# 一键演示解说词（中文）",
    "en": "# One-click demo narration transcript (English)",
}
SUBTITLES = {
    "zh": "由 `npm run tts` 从 src/demo/scripts.ts 与 src/locales/zh/demo.json 生成，"
    "配音 edge-tts {voice}（女声）。音频路径 public/tts/zh/<key>.mp3。",
    "en": "Generated by `npm run tts` from src/demo/scripts.ts and "
    "src/locales/en/demo.json; voice edge-tts {voice} (female). "
    "Audio at public/tts/en/<key>.mp3.",
}


def lookup(data, dotted: str):
    cur = data
    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur if isinstance(cur, str) else None


def load_scripts():
    src = SCRIPTS_TS.read_text(encoding="utf-8")
    scripts = []
    for block in SCRIPT_RE.finditer(src):
        body = block.group(1)
        head = HEAD_RE.search(body)
        if not head:
            continue
        beats = [m.groupdict() for m in BEAT_RE.finditer(body)]
        for b in beats:
            b["ms"] = int(b["ms"])
            rest = b.pop("rest") or ""
            f = FOCUS_RE.search(rest)
            z = ZOOM_RE.search(rest)
            b["focus"] = f["focus"] if f else None
            b["zoom"] = float(z["zoom"]) if z else None
        # Self-check: the parser must see every tooltip in the block. A drifting
        # pattern would otherwise ship a transcript that is quietly short.
        declared = len(TOOLTIP_COUNT_RE.findall(body))
        if declared != len(beats):
            sys.exit(
                f"beat parser out of date: {head['id'] if head else '?'} declares "
                f"{declared} tooltip beats, parsed {len(beats)}"
            )
        scripts.append({"id": head["id"], "nameKey": head["nameKey"], "beats": beats})
    if not scripts:
        sys.exit("no demo scripts parsed from src/demo/scripts.ts")
    return scripts


def load_locale(lang: str) -> dict:
    path = ROOT / "src" / "locales" / lang / "demo.json"
    return json.loads(path.read_text(encoding="utf-8"))


def fnv1a(text: str) -> str:
    """32-bit FNV-1a over UTF-16 code units — must match the JS copy in
    src/demo/narration.ts, which is what lets the app tell that a caption was
    edited after its audio was generated."""
    h = 0x811C9DC5
    for unit in text.encode("utf-16-le"):
        h ^= unit
        h = (h * 0x01000193) & 0xFFFFFFFF
    return format(h, "x")


MANIFEST = AUDIO_DIR / "manifest.json"


def read_manifest() -> dict:
    if not MANIFEST.exists():
        return {}
    try:
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def mp3_duration(path: Path):
    if shutil.which("afinfo"):
        out = subprocess.run(["afinfo", str(path)], capture_output=True, text=True).stdout
        m = re.search(r"estimated duration:\s*([\d.]+)", out)
        if m:
            return float(m.group(1))
    if shutil.which("ffprobe"):
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "csv=p=0", str(path)],
            capture_output=True, text=True,
        ).stdout
        m = re.search(r"([\d.]+)", out)
        if m:
            return float(m.group(1))
    return None


async def synth(sem, text: str, voice: str, path: Path, force: bool) -> str:
    if path.exists() and path.stat().st_size > 0 and not force:
        return "skip"
    async with sem:
        last = None
        for attempt in range(RETRIES):
            try:
                await edge_tts.Communicate(text, voice).save(str(path))
                if path.exists() and path.stat().st_size > 0:
                    return "ok"
                raise RuntimeError("empty output file")
            except Exception as exc:  # noqa: BLE001 — retry any transport error
                last = exc
                await asyncio.sleep(1.5 * (attempt + 1))
        raise RuntimeError(f"{path.name}: {last}")


def write_transcript(lang, scripts, texts, durations):
    lines = [
        TITLES[lang],
        "",
        SUBTITLES[lang].format(voice=VOICES[lang]),
        "",
    ]
    for sc in scripts:
        name = lookup(texts, sc["nameKey"]) or sc["nameKey"]
        lines.append(f"## {sc['id']} · {name}")
        lines.append("")
        for b in sc["beats"]:
            text = lookup(texts, b["key"])
            if text is None:
                raise KeyError(f"missing locale key {b['key']!r} in {lang}/demo.json")
            dur = durations.get((lang, b["key"]))
            dur_s = f"{dur:.1f}s" if dur else "?"
            # pointer = the data-id the fake cursor sits on while speaking
            pointer = f" · pointer {b['focus']}" if b.get("focus") else ""
            lines.append(
                f"### {b['id']} · {b['chapter']} · caption {b['ms']} ms · "
                f"audio {dur_s} · {b['key']}{pointer}"
            )
            lines.append("")
            lines.append(text)
            lines.append("")
    out = HERE / f"transcript.{lang}.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="regenerate existing audio")
    ap.add_argument("--transcript-only", action="store_true", help="skip TTS")
    args = ap.parse_args()

    scripts = load_scripts()
    locales = {lang: load_locale(lang) for lang in LANGS}
    missing = [
        (sc["id"], b["key"], lang)
        for sc in scripts
        for b in sc["beats"]
        for lang in LANGS
        if lookup(locales[lang], b["key"]) is None
    ]
    if missing:
        for m in missing:
            print(f"missing locale key: {m}", file=sys.stderr)
        sys.exit(1)

    failures = []
    # lang -> key -> hash of the text the existing mp3 was actually made from.
    # Only regenerated clips update it, so the manifest always describes what
    # is on disk; the app uses it to refuse to play a clip whose caption has
    # since been edited (see src/demo/narration.ts).
    manifest = read_manifest()
    if not args.transcript_only:
        AUDIO_DIR.mkdir(parents=True, exist_ok=True)
        jobs = []
        sem = asyncio.Semaphore(CONCURRENCY)
        for lang in LANGS:
            lang_dir = AUDIO_DIR / lang
            lang_dir.mkdir(parents=True, exist_ok=True)
            for sc in scripts:
                for b in sc["beats"]:
                    path = lang_dir / f"{b['key']}.mp3"
                    jobs.append(
                        (lang, b["key"], lookup(locales[lang], b["key"]), path,
                         synth(sem, lookup(locales[lang], b["key"]), VOICES[lang], path, args.force))
                    )

        async def run_all():
            results = await asyncio.gather(
                *(j[4] for j in jobs), return_exceptions=True
            )
            for (lang, key, text, _path, _fut), res in zip(jobs, results):
                if isinstance(res, Exception):
                    failures.append(f"{lang}/{key}: {res}")
                    print(f"FAIL {lang}/{key}: {res}")
                elif res == "ok":
                    manifest.setdefault(lang, {})[key] = fnv1a(text)
                    print(f"ok   {lang}/{key}.mp3")

        asyncio.run(run_all())
        MANIFEST.write_text(
            json.dumps(manifest, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        stale = [
            f"{lang}/{key}"
            for lang in LANGS
            for sc in scripts
            for b in sc["beats"]
            for key in [b["key"]]
            if (lang, key) not in {(l, k) for l in manifest for k in manifest[l]}
        ]
        if stale:
            print(
                f"note: {len(stale)} clip(s) predate the manifest — run with --force "
                "to have the app trust them",
                file=sys.stderr,
            )

    durations = {}
    for lang in LANGS:
        for sc in scripts:
            for b in sc["beats"]:
                path = AUDIO_DIR / lang / f"{b['key']}.mp3"
                if path.exists():
                    d = mp3_duration(path)
                    if d:
                        durations[(lang, b["key"])] = d

    for lang in LANGS:
        out = write_transcript(lang, scripts, locales[lang], durations)
        print(f"wrote {out.relative_to(ROOT)}")

    if failures:
        print(f"\n{len(failures)} audio generation failure(s)", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
